global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: aggregator
    static_configs:
      - targets: ['aggregator:8000']
        labels: { service: aggregator }

  - job_name: user-sync
    static_configs:
      - targets: ['user-sync:8001']
        labels: { service: user-sync }

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
